[env]
# Fixes color stripping when SSHing into remote servers
TERM = "xterm-256color"

[window]
# Gives your terminal text a little breathing room from the edges
padding = { x = 12, y = 12 }
dynamic_padding = true

# Glassmorphism settings (Picom will handle the actual blur)
opacity = 0.85

[font]
# Explicitly setting the size so it doesn't shrink
size = 11.5

[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[colors.cursor]
text   = '#282828'
cursor = '#d65d0e' 
