[env]
# Fixes color stripping when SSHing into remote servers
TERM = "xterm-256color"

[window]
# Gives your terminal text a little breathing room from the edges
padding = { x = 12, y = 12 }
dynamic_padding = true

# Glassmorphism settings (Picom will handle the actual blur)
opacity = 0.90

[font]
normal = { family = "CaskaydiaCove NF", style = "Regular" }
bold = { family = "CaskaydiaCove NF", style = "Bold" }
italic = { family = "CaskaydiaCove NF", style = "Italic" }
bold_italic = { family = "CaskaydiaCove NF", style = "Bold Italic" }
size = 11

[colors.primary]
background = '#0D0E12'
foreground = '#E2E4E9'

# Retro Arcade colors
[colors.normal]
black   = '#0D0E12'
red     = '#FF0000' # Blinky Red
green   = '#00FF00'
yellow  = '#FCE700' # Pac-Man Yellow
blue    = '#0000D7' # Maze Blue
magenta = '#FFB8FF' # Pinky Pink
cyan    = '#00D7FF' # Inky Cyan
white   = '#E2E4E9'

# Bright colors
[colors.bright]
black   = '#505860'
red     = '#FF5555'
green   = '#55FF55'
yellow  = '#FFFF55'
blue    = '#5555FF'
magenta = '#FFBBFF'
cyan    = '#55FFFF'
white   = '#FFFFFF'

[colors.cursor]
text   = '#0D0E12'
cursor = '#FCE700'

